// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentProgress.Infrastructure.Data;

#nullable disable

namespace StudentProgress.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentProgress.Domain.Entities.Progress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AssessmentScore")
                        .HasColumnType("float");

                    b.Property<int>("AssignmentCompleted")
                        .HasColumnType("int");

                    b.Property<double>("CompletionPercentage")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("datetime2");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("ProgressRecords");

                    b.HasData(
                        new
                        {
                            Id = new Guid("27629f06-9e5a-44f2-9db6-17bae490a961"),
                            AssessmentScore = 60.0,
                            AssignmentCompleted = 3,
                            CompletionPercentage = 65.0,
                            LastActivity = new DateTime(2025, 7, 12, 20, 21, 5, 842, DateTimeKind.Utc).AddTicks(5273),
                            Score = 68.0,
                            StudentId = new Guid("a1785ad7-9bf2-4c98-b425-7fdc6731a7b8"),
                            Subject = "Math",
                            TimeSpent = new TimeSpan(0, 4, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("268fcba3-5f37-4172-8594-21839bde4b08"),
                            AssessmentScore = 88.0,
                            AssignmentCompleted = 4,
                            CompletionPercentage = 80.0,
                            LastActivity = new DateTime(2025, 7, 8, 20, 21, 5, 842, DateTimeKind.Utc).AddTicks(5284),
                            Score = 85.0,
                            StudentId = new Guid("fdea37af-a680-4f04-b0a0-586af2ab6785"),
                            Subject = "Reading",
                            TimeSpent = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("3796ec0c-5a52-4314-a44b-aa41b8aa1383"),
                            AssessmentScore = 95.0,
                            AssignmentCompleted = 5,
                            CompletionPercentage = 95.0,
                            LastActivity = new DateTime(2025, 7, 10, 20, 21, 5, 842, DateTimeKind.Utc).AddTicks(5287),
                            Score = 93.0,
                            StudentId = new Guid("ac589662-1e08-4d48-98aa-89ba6d8909f7"),
                            Subject = "Science",
                            TimeSpent = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("9436714d-586f-47a3-8ce2-4e1343bd5b70"),
                            AssessmentScore = 52.0,
                            AssignmentCompleted = 2,
                            CompletionPercentage = 50.0,
                            LastActivity = new DateTime(2025, 6, 13, 20, 21, 5, 842, DateTimeKind.Utc).AddTicks(5290),
                            Score = 55.0,
                            StudentId = new Guid("249b8e7e-a11d-4bc3-a541-b29f9d699e00"),
                            Subject = "Social Studies",
                            TimeSpent = new TimeSpan(0, 3, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("0408b65e-781a-41d8-8e6c-88d2284c1f90"),
                            AssessmentScore = 68.0,
                            AssignmentCompleted = 3,
                            CompletionPercentage = 70.0,
                            LastActivity = new DateTime(2025, 7, 3, 20, 21, 5, 842, DateTimeKind.Utc).AddTicks(5292),
                            Score = 72.0,
                            StudentId = new Guid("b224b27e-eb60-480a-87a5-c4918eace424"),
                            Subject = "Math",
                            TimeSpent = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("f3137381-2edc-4f32-9e6c-81abeae40f9d"),
                            AssessmentScore = 85.0,
                            AssignmentCompleted = 4,
                            CompletionPercentage = 88.0,
                            LastActivity = new DateTime(2025, 7, 11, 20, 21, 5, 842, DateTimeKind.Utc).AddTicks(5296),
                            Score = 90.0,
                            StudentId = new Guid("42269daf-6352-463b-b129-2bc139f3fa1f"),
                            Subject = "Reading",
                            TimeSpent = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("87cb4a63-52ec-4cea-81b4-767b918bb863"),
                            AssessmentScore = 91.0,
                            AssignmentCompleted = 5,
                            CompletionPercentage = 92.0,
                            LastActivity = new DateTime(2025, 7, 12, 20, 21, 5, 842, DateTimeKind.Utc).AddTicks(5299),
                            Score = 94.0,
                            StudentId = new Guid("1dfb94ac-e4e6-4c73-a599-cb347d9e8e7c"),
                            Subject = "Science",
                            TimeSpent = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("d0376791-7a72-4ac0-a387-670ee141c61c"),
                            AssessmentScore = 42.0,
                            AssignmentCompleted = 1,
                            CompletionPercentage = 40.0,
                            LastActivity = new DateTime(2025, 5, 29, 20, 21, 5, 842, DateTimeKind.Utc).AddTicks(5301),
                            Score = 45.0,
                            StudentId = new Guid("36e13d97-7999-4259-866b-965ab7c6ae0b"),
                            Subject = "Social Studies",
                            TimeSpent = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("7d6f6b81-afba-49e8-8c3c-76e9c7e909e9"),
                            AssessmentScore = 75.0,
                            AssignmentCompleted = 3,
                            CompletionPercentage = 78.0,
                            LastActivity = new DateTime(2025, 7, 9, 20, 21, 5, 842, DateTimeKind.Utc).AddTicks(5305),
                            Score = 80.0,
                            StudentId = new Guid("966131a9-28e4-472e-9903-92f2620cdece"),
                            Subject = "Math",
                            TimeSpent = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("587726af-7c3b-4e81-b42b-358d0899e0a6"),
                            AssessmentScore = 83.0,
                            AssignmentCompleted = 4,
                            CompletionPercentage = 85.0,
                            LastActivity = new DateTime(2025, 7, 7, 20, 21, 5, 842, DateTimeKind.Utc).AddTicks(5309),
                            Score = 88.0,
                            StudentId = new Guid("c60d716c-22fc-46cb-9475-797f9f1d5e91"),
                            Subject = "Reading",
                            TimeSpent = new TimeSpan(0, 10, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("StudentProgress.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1785ad7-9bf2-4c98-b425-7fdc6731a7b8"),
                            DateOfBirth = new DateTime(2019, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Aiden Carter",
                            Grade = "K"
                        },
                        new
                        {
                            Id = new Guid("fdea37af-a680-4f04-b0a0-586af2ab6785"),
                            DateOfBirth = new DateTime(2018, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bella Chen",
                            Grade = "1"
                        },
                        new
                        {
                            Id = new Guid("ac589662-1e08-4d48-98aa-89ba6d8909f7"),
                            DateOfBirth = new DateTime(2017, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Caleb Davis",
                            Grade = "2"
                        },
                        new
                        {
                            Id = new Guid("249b8e7e-a11d-4bc3-a541-b29f9d699e00"),
                            DateOfBirth = new DateTime(2016, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Diana Evans",
                            Grade = "3"
                        },
                        new
                        {
                            Id = new Guid("b224b27e-eb60-480a-87a5-c4918eace424"),
                            DateOfBirth = new DateTime(2015, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ethan Flores",
                            Grade = "4"
                        },
                        new
                        {
                            Id = new Guid("42269daf-6352-463b-b129-2bc139f3fa1f"),
                            DateOfBirth = new DateTime(2014, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Fiona Gomez",
                            Grade = "5"
                        },
                        new
                        {
                            Id = new Guid("1dfb94ac-e4e6-4c73-a599-cb347d9e8e7c"),
                            DateOfBirth = new DateTime(2013, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Gabriel Harris",
                            Grade = "6"
                        },
                        new
                        {
                            Id = new Guid("36e13d97-7999-4259-866b-965ab7c6ae0b"),
                            DateOfBirth = new DateTime(2012, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Hannah Ibrahim",
                            Grade = "7"
                        },
                        new
                        {
                            Id = new Guid("966131a9-28e4-472e-9903-92f2620cdece"),
                            DateOfBirth = new DateTime(2011, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ian Jackson",
                            Grade = "8"
                        },
                        new
                        {
                            Id = new Guid("c60d716c-22fc-46cb-9475-797f9f1d5e91"),
                            DateOfBirth = new DateTime(2010, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Jasmine Kim",
                            Grade = "9"
                        },
                        new
                        {
                            Id = new Guid("b6a2ad45-a18d-4620-8c04-54ce07440f6d"),
                            DateOfBirth = new DateTime(2009, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Kai Lee",
                            Grade = "10"
                        },
                        new
                        {
                            Id = new Guid("9f9c3a49-7c19-4196-8892-41986dc371ad"),
                            DateOfBirth = new DateTime(2008, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Liam Martinez",
                            Grade = "11"
                        },
                        new
                        {
                            Id = new Guid("e249763a-5c2e-476d-bfba-92074f35ab42"),
                            DateOfBirth = new DateTime(2007, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mia Nguyen",
                            Grade = "12"
                        },
                        new
                        {
                            Id = new Guid("c69cc368-dc8f-4ba6-a207-dd4536c27917"),
                            DateOfBirth = new DateTime(2014, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Noah Patel",
                            Grade = "5"
                        },
                        new
                        {
                            Id = new Guid("64dd9809-3856-40dc-9b5e-d26cd8b1f3c9"),
                            DateOfBirth = new DateTime(2012, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Olivia Quinn",
                            Grade = "7"
                        },
                        new
                        {
                            Id = new Guid("fdad5b13-e4c6-40e6-b523-299c5543b6f5"),
                            DateOfBirth = new DateTime(2017, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Parker Rivera",
                            Grade = "2"
                        },
                        new
                        {
                            Id = new Guid("33874a99-f0c5-4aba-aa22-e215d1c113e9"),
                            DateOfBirth = new DateTime(2011, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Quinn Smith",
                            Grade = "8"
                        },
                        new
                        {
                            Id = new Guid("d94a3809-0a05-4fcc-94f9-80f58702e8a2"),
                            DateOfBirth = new DateTime(2010, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Riley Thompson",
                            Grade = "9"
                        },
                        new
                        {
                            Id = new Guid("10010fbc-7f1a-4b53-b487-d38f6a73f001"),
                            DateOfBirth = new DateTime(2009, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Sophia Upton",
                            Grade = "10"
                        },
                        new
                        {
                            Id = new Guid("04dfb491-d17d-48aa-a3ed-dea663221b53"),
                            DateOfBirth = new DateTime(2008, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Tyler Vasquez",
                            Grade = "11"
                        });
                });

            modelBuilder.Entity("StudentProgress.Domain.Entities.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9214c21c-24bf-4e04-94fb-eb4a119c4e69"),
                            FullName = "Emily Johnson"
                        });
                });

            modelBuilder.Entity("StudentProgress.Domain.Entities.Progress", b =>
                {
                    b.HasOne("StudentProgress.Domain.Entities.Student", "Student")
                        .WithMany("ProgressRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentProgress.Domain.Entities.Student", b =>
                {
                    b.HasOne("StudentProgress.Domain.Entities.Teacher", null)
                        .WithMany("AssignedStudents")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("StudentProgress.Domain.Entities.Student", b =>
                {
                    b.Navigation("ProgressRecords");
                });

            modelBuilder.Entity("StudentProgress.Domain.Entities.Teacher", b =>
                {
                    b.Navigation("AssignedStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
